#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

$autoloadPath=__DIR__ . '/vendor/autoload.php';
require($autoloadPath);
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
$vendorPath = dirname($autoloadPath);
$config=require('common/config/console.php');
$application = new yii\console\Application($config);
$application->setVendorPath($vendorPath);
$exitCode = $application->run();
exit($exitCode);
